name: Build and deploy DY.CO Production
on:
  push:
    paths:
      - 'dyco/**'
    branches:
      - main
  workflow_dispatch:
      inputs:
        purpose:
          description: 'Please fill the purpose of manual trigger'
          required: true
          default: ''

env:
  GATSBY_CONTENTFUL_ACCESS_TOKEN: ${{ secrets.GATSBY_CONTENTFUL_ACCESS_TOKEN_DYCO_PROD}}
  GATSBY_CONTENTFUL_SPACE_ID: ${{ GATSBY_CONTENTFUL_SPACE_ID_DYCO_PROD }}
  SERVER_URL: "phpstack-693884-2329394.cloudwaysapps.com"
jobs:
  build_and_deploy:
    runs-on: gha-internal
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Print reason of rerun when manual trigger
        if: ${{  github.event.inputs.purpose }}
        run: |
          echo "[INFO]: ${{ github.event.inputs.purpose }}"
      - name: Use Node.js 16
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Setup connection to remote server
        run: |
          sudo apt-get -yq update && sudo apt-get -yqq install ssh
          mkdir -p ~/.ssh
          ssh-keyscan ${{ env.SERVER_URL }} >> ~/.ssh/known_hosts
          echo "${{ secrets.PRIVATE_SSH_KEY }}" > ~/.ssh/github_actions_ssh_key
          chmod 600 ~/.ssh/github_actions_ssh_key
      - name: Build
        working-directory: ./dyco
        run: |
          npm install && npm run build
      - name: Deploy to Cloudways
        working-directory: ./dyco
        run: |
          echo "put -r public/* /public_html/" | sftp -i ~/.ssh/github_actions_ssh_key ${{ secrets.PROD_ENV_DYCO_SFTP_USER }}@${{ env.SERVER_URL }}
